ecommerce/store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path('<slug:slug>', views.ProductByCategory.as_view(), name="product_by_category"),
    path('detail/<slug:slug>', views.ProductDetailView.as_view(), name="product_detail"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.core.urls', namespace='core')),
    path('store/', include('ecommerce.store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/store/models.py
import random
from uuid import uuid4
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone

from ecommerce.category.models import Category, Brand


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='name', help_text='Required')
    web_id = models.CharField(unique=True, max_length=80, null=True, blank=True)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    description = models.TextField(verbose_name='description', help_text='Not required', null=True, blank=True)
    image = models.ImageField(upload_to="product_image/", default="product_image/default.png")
    main_price = models.IntegerField(verbose_name='main price', help_text='price must not be less than 0')

    # relations
    category = models.ForeignKey(Category, related_name="product", on_delete=models.CASCADE)

    # utilities
    unique_id = models.CharField(max_length=100, null=True, blank=True)
    date_created = models.DateTimeField(null=True, blank=True)
    date_updated = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        data = list(range(1000, 10000))
        random.shuffle(data)
        if self.unique_id is None:
            self.unique_id = str(uuid4()).split("-")[4]
        if self.web_id is None:
            self.web_id= str(data[12])
        if self.slug is None:
            self.slug = slugify("{} {} {}".format(self.name,self.web_id, self.unique_id))
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        self.slug = slugify("{} {} {}".format(self.name, self.web_id, self.unique_id))
        self.date_updated = timezone.localtime(timezone.now())
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    

class ProductAttribute(models.Model):
    name = models.CharField(max_length=255, unique=True, help_text="format: required, unique, max-255")
    description = models.TextField(null=True, blank=True, help_text="format: not required")

    def __str__(self):
        return self.name
    
class ProductAttributeValue(models.Model):
    product_attribute = models.ForeignKey(ProductAttribute, related_name="product_attribute",
                                        on_delete=models.PROTECT)
    attribute_value = models.CharField(max_length=200, verbose_name="attribute value",
                                    help_text="format: required, max-length=200 characters")
    
    def __str__(self):
        return self.attribute_value
    

class ProductType(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name="type of product",
                            help_text="format: required, must be unique, max of 200 characters")
    product_type_attributes = models.ManyToManyField(ProductAttribute,
                                                    related_name="product_type_attributes",
                                                    through="ProductTypeAttribute")
    
    def __str__(self):
        return self.name
    

class ProductTypeAttribute(models.Model):
    product_attribute =  models.ForeignKey(ProductAttribute, related_name="productattribute",
                                           on_delete=models.PROTECT)
    product_type =  models.ForeignKey(ProductType, related_name="producttype",
                                           on_delete=models.PROTECT)
    
    class Meta:
        unique_together = (("product_attribute", "product_type"),)        
    

class ProductInventory(models.Model):
    sku = models.CharField(max_length=20, unique=True, help_text="stock keeping price", null=True)
    upi = models.CharField(max_length=30, unique=True, help_text="universal product id", null=True)
    store_price = models.IntegerField(verbose_name='Regular store price', help_text='price must not be less than 0')
    sale_price = models.IntegerField(verbose_name='sale price', help_text='price must not be less than 0')
    is_active = models.BooleanField(default=True, verbose_name="product visibility", help_text="checking: True= Product visible")
    is_default = models.BooleanField(default=False, verbose_name="default selection", help_text="Format: true= sub product selected")
    date_created = models.DateTimeField(auto_now_add=True, verbose_name="date sub-product created")
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date sub-product updated")

    # relations
    product = models.ForeignKey(Product, related_name="product", on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, related_name="brand", on_delete=models.CASCADE)
    product_type = models.ForeignKey(ProductType, related_name="product_type",
                                    on_delete=models.PROTECT)
    attribute_values = models.ManyToManyField(ProductAttributeValue,
                                            related_name="product_attribute_values",
                                            through="ProductAttributeValues",)

    def __str__(self):
        return self.product.name
    

class ProductAttributeValues(models.Model):
    attributevalues = models.ForeignKey(ProductAttributeValue,
                                        related_name="attributevaluevalues",
                                        on_delete=models.PROTECT,)
    productinventory = models.ForeignKey(ProductInventory,
                                        related_name="productattributevaluevalues",
                                        on_delete=models.PROTECT,)
    
    class Meta:
        unique_together = (("attributevalues", "productinventory"),)

    def __str__(self):
        return self.attributevalues.attribute_value


class Media(models.Model):
    product_inventory = models.ForeignKey(ProductInventory,
                                        related_name="media_product_inventory",
                                        on_delete=models.PROTECT,)
    img_url = models.ImageField(verbose_name="product image", upload_to="product_image/",
                                default="product_image/default.png",help_text="format: required, default-default.png")
    alt_text = models.CharField(max_length=255, verbose_name="alternative text",
                                help_text="format: required, max-255")
    is_feature = models.BooleanField(default=False, verbose_name="product default image",)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "product image"
        verbose_name_plural = "product images"


class Stock(models.Model):
    product_inventory = models.OneToOneField(ProductInventory,
                        related_name="product_inventory", on_delete=models.PROTECT)
    last_checked = models.DateTimeField(null=True, blank=True,
                    verbose_name="inventory last stock check date")
    units = models.IntegerField(default=0, verbose_name="units/qty of stock")
    units_sold = models.IntegerField(default=0, verbose_name="units sold to date")

    def __str__(self):
        return self.product_inventory.product.name
    

ecommerce/store/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import DetailView , ListView, TemplateView

from ecommerce.category.models import Category
from .models import Product, ProductInventory

   
class ProductByCategory(DetailView):
    model = Category
    template_name = 'store/store.html'
    context_object_name = 'category'

    def get_context_data(self, *args, **kwargs):
        context = super(ProductByCategory,
             self).get_context_data(*args, **kwargs)
        
        category = context["category"]
        context["products"] = Product.objects.filter(category=category)  
        # context["products"] = ProductInventory.objects.filter(product__category=category).filter(is_default=True)    
        return context

class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView,
             self).get_context_data(*args, **kwargs)
        
        product = context["product"]
        context["product_inventory"] = ProductInventory.objects.filter(product=product).filter(is_default=True)
        return context

# class ProductByCategory(View):
#     def get(self, request, slug):
#         category = get_object_or_404(Category,slug=slug)
#         products = Product.objects.filter(category=category)

#         context = {'products':products, 'category':category}

#         return render(request, "store/store.html", context )

templates/store/product_detail.html
{% extends "../base.html" %}
{% block title %}Product By Categories {% endblock %}

{% block sub_content %}

<div class="card">
    <div class="card-body">
        <div class="row gx-5">
            {% for product in product_inventory %}
            <div class="col-md-7">
                <img src="{{product.product.image.url}}" class="card-img-top" alt="{{image.alt_text}}">
                
                    <div class="row mt-4">
                        {% for image in product.media_product_inventory.all %}
                        <div class="col-3">
                            <img src="{{image.img_url.url}}" class="card-img-top" alt="{{image.alt_text}}" style="height: 127px;">
                        </div>
                        {% endfor %}
                    </div>
            </div>
            
            <div class="col-md-5">
                <h2>{{product.product.name}}</h2>

                <!-- product id -->
                <div class="d-flex mt-4">
                    <h5>Universal Product ID:</h5>
                    <h5 class="text-primary ms-3">{{product.upi}}</h5>
                </div>

                <!-- rating -->
                <div class="rating my-4">
                    <div class="stars">
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                    </div>
                    <span class="review-no">41 reviews</span>
                </div>

                <!-- decription -->
                <p class=" ">{{product.product.description}} </p>

                <!-- price -->
                <div class="price d-flex">
                    <h3>Current Price:</h3>
                    <h5 class="ms-3 mt-sm-2 mt-1 text-warning">&#8358;{{product.store_price}}</h5>
                </div>

                <!-- discount -->
                <p class="mt-4"><strong>91</strong>% of buyers enjoyed this product!<strong>(87 votes)</strong></p>

                <!-- sizes -->
                <div class="price d-flex mt-4">
                    <h3>Sizes:</h3>
                    <div class="checkboxes ms-4 mt-sm-2 mt-1">
                        <div class="d-flex">
                            <div class="form-check ms-2">
                                <label class="form-check-label fw-bold" for="small">
                                    S
                                </label>
                                <input class="form-check-input" type="radio" name="small" id="small">
                            </div>
                            <div class="form-check ms-2">
                                <label class="form-check-label fw-bold" for="medium">
                                    M
                                </label>
                                <input class="form-check-input" type="radio" name="medium" id="medium">
                            </div>
                            <div class="form-check ms-2">
                                <label class="form-check-label fw-bold" for="large">
                                    L
                                </label>
                                <input class="form-check-input" type="radio" name="large" id="large">
                            </div>
                            <div class="form-check ms-2">
                                <label class="form-check-label fw-bold" for="xtra-large">
                                    XL
                                </label>
                                <input class="form-check-input" type="radio" name="xlarge" id="xtra-large">
                            </div>
                            <div class="form-check ms-2">
                                <label class="form-check-label fw-bold" for="xx-large">
                                    XXL
                                </label>
                                <input class="form-check-input" type="radio" name="xxlarge" id="xx-large">
                            </div>

                        </div>
                    </div>
                </div>

                <!-- color -->
                <div class="d-flex my-5">
                    <h4>color:</h4>
                    <div class="all-colors d-flex">
                        <span class="ms-3 fw-bold bg-danger p-1 text-white">Red</span>
                        <span class="ms-3 fw-bold bg-primary p-1 text-white">Blue</span>
                        <span class="ms-3 fw-bold bg-success p-1 text-white">Green</span>
                        <span class="ms-3 fw-bold bg-dark p-1 text-white">black</span>
                    </div>
                </div>

                <!-- button -->
                <button class="btn btn-secondary fw-bold btn-sm w-50">Add to Cart</button>
            </div>

            
            
            {% endfor %}
        </div>
        
    </div>
</div>
    

{% endblock %}

templates/store/store.html
{% extends "../base.html" %}
{% block title %}Product By Categories {% endblock %}

{% block sub_content %}
<div class="card text-center shadow">
    <div class="card-body">
        <h4 class="pt-0 card-title">{{category.name}}</h4>
    </div>
</div>

<div class="row pt-4">
    {% for product in products %}
    <div class="col-4 col-md-3 col-lg-2">
        <div class="card">
            <!-- {% for image in product.media_product_inventory.all %}
                {% if image.is_feature %}
                <img src="{{image.img_url.url}}" class="card-img-top" alt="{{image.alt_text}}">
                {% endif %}
            {% endfor %} -->
            <img src="{{product.image.url}}" class="card-img-top" alt="{{image.alt_text}}">
            <div class="card-body">
              
              <p class="card-text small">{{product.name|slice:":20"}}...</p>
              <h5 class="card-title">&#8358;{{product.main_price}}</h5>
              <a href="{% url 'store:product_detail' product.slug %}" class="btn btn-secondary w-100 fw-bold">View Detail</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}